ecobionics/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('home/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/home/', permanent=True)), ] + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              # static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \

home/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.update_profile, name='profile'),
    path('', views.AnnounceListView.as_view(), name='index'),
    path('info/', views.info, name='info'),
    url(r'^want_to_go/(?P<announce_pk>\d+)$', views.want_to_go, name='want-to-go'),
    url(r'^comment/(?P<announce_pk>\d+)$', views.add_comment, name='add-comment'),
    url(r'^tag/(?P<tag_pk>\d+)$', views.TagAnnounceListView.as_view(), name='tag-announces'),
    path('kaganov/', views.kaganov, name='kaganov'),
    path('zhuk/', views.zhuk, name='zhuk'),
    path('karpenko/', views.karpenko, name='karpenko'),
    path('redko/', views.redko, name='redko'),
    path('yushenko/', views.yushenko, name='yushenko'),
    path('committee/', views.committee, name='committee'),
    path('plan/', views.plan, name='plan'),
    path('literature/', views.literature, name='literature'),
]

home/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Теги объявлений
class Tag(models.Model):
    tag_ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]

    # Получение URL для отдельного тега
    def get_absolute_url(self):
        return reverse('tag-detail', args=[str(self.tag_ID)])

    def __str__(self):
        return self.name


# Возвращает путь, в который нужно сохранить файл пользователя
def user_directory_path(instance, filename):
    # Файл будет сохранён в MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


def image_path(instance, filename):
    return 'images/{0}'.format(filename)


# Объявления
class Announce(models.Model):
    announce_ID = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, unique=True)
    headline = models.TextField(null=True, blank=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    preview_image = models.ImageField(upload_to='images', null=True, blank=True)
    # Ссылка на превью-картинку
    # preview_image = models.CharField(max_length=300, null=True, blank=True)
    announce_tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    presentation = models.FileField(upload_to='files', null=True, blank=True)
    document = models.FileField(upload_to='files', null=True, blank=True)

    # Метаданные класса
    class Meta:
        # Способ сортировки: сначала идут самые свежие объявления
        ordering = ["-publication_date"]

    # Получение URL для отдельного объявления
    def get_absolute_url(self):
        return reverse('announce-detail', args=[str(self.announce_ID)])

    def __str__(self):
        return self.title


# Профили пользователей
class Profile(models.Model):
    profile_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    registration_date = models.DateField(auto_now_add=True)
    # События, на которые пользователь хочет пойти
    want_to_go_announces = models.ManyToManyField(Announce, blank=True, verbose_name="Хочу пойти")


# Функция для создания/обновления профиля пользователя при создании/обновлении пользователя
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


# Комментарии
class Comment(models.Model):
    comment_ID = models.AutoField(primary_key=True)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    announce = models.ForeignKey(Announce, on_delete=models.CASCADE)

    class Meta:
        # Задаём порядок сортировки комментариев по датам
        ordering = ["date"]

    # Получение URL для отдельного комментария
    def get_absolute_url(self):
        return reverse('comment-detail', args=[str(self.comment_ID)])

    def __str__(self):
        return self.content

home/forms.py
from django.contrib.auth.models import User
from django import forms
from home.models import Profile, Tag, Comment
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


# Форма добавления комментария
class AddCommentForm(forms.Form):
    # Поле формы
    comment_content = forms.CharField(widget=forms.Textarea, required=True)

    # Проверка правильности введённых данных
    def clean_renewal_date(self):
        data = self.cleaned_data['comment_content']
        return data


# Форма для введения данных пользователя
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


# Форма для введения данных профиля пользователя
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('want_to_go_announces',)


# Формы для регистрации
class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'email')


# Форма изменения данных пользователя
class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = User
        fields = ('username', 'email')

home/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.views import generic
from django.http import HttpResponseRedirect, Http404
from django.db.models import Count
from datetime import datetime, timedelta

from home.forms import UserForm, ProfileForm, CustomUserCreationForm
from home.models import Announce, Comment, Tag


# Информация о сайте
def info(request):
    # render() - отрисовка HTML-шаблона info.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'info.html',
    )


# Отображение списка объявлений
class AnnounceListView(generic.ListView):
    model = Announce
    # Имя переменной контекста в шаблоне
    context_object_name = 'announce_list'
    # Получаем все объявления
    queryset = Announce.objects.all()
    # Расположение шаблона и его имя
    template_name = 'templates/home/announce_list.html'
    # Количество объявлений в отображении (на одной странице)
    paginate_by = 10


# Поставить "хочу пойти" на объявление
@login_required(login_url='/home/login/')
def want_to_go(request, announce_pk):
    try:
        announce = Announce.objects.get(pk=announce_pk)
    except Announce.DoesNotExist:
        raise Http404("Announce does not exist")

    if request.user.profile.want_to_go_announces.filter(announce_ID=announce.announce_ID).exists():
        # Удаляем "хочу пойти"
        request.user.profile.want_to_go_announces.remove(announce)
    else:
        # Добавляем "хочу пойти"
        request.user.profile.want_to_go_announces.add(announce)

    request.user.profile.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# Добавить комментарий
@login_required(login_url='/home/login/')
def add_comment(request, announce_pk):
    try:
        announce = Announce.objects.get(pk=announce_pk)
    except Announce.DoesNotExist:
        raise Http404("Announce does not exist")
    if request.method == 'POST':
        comment_content = request.POST.get('comment_field_' + str(announce.announce_ID))
        Comment.objects.create(content=comment_content, user=request.user, announce=announce)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# Обновление профиля пользователя
@login_required(login_url='/home/login/')
# Указываем, что это транзакция. Если она не выполнится успешно, то будет откат
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('index')
        else:
            pass
            # messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profiles/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


# Регистрация пользователя
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    # Адрес страницы, на который нужно совершить переход после успешного заполнения формы
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


# Объявления по тегу
class TagAnnounceListView(generic.ListView):
    model = Announce
    context_object_name = 'announce_list'
    # Расположение шаблона
    template_name = 'home/tag_announce_list.html'
    paginate_by = 10

    # Функция формирования контекста
    def get_context_data(self, **kwargs):
        context = super(TagAnnounceListView, self).get_context_data(**kwargs)
        try:
            tag = Tag.objects.get(tag_ID=self.kwargs['tag_pk'])
        except Tag.DoesNotExist:
            raise Http404("Tag does not exist")
        context['tag'] = tag

        return context

    def get_queryset(self):
        try:
            tag = Tag.objects.filter(tag_ID=self.kwargs['tag_pk'])
        except Tag.DoesNotExist:
            raise Http404("Tag does not exist")
        return Announce.objects.filter(announce_tags__in=tag)


# Страница с информацией о Ю. Т. Каганове
def kaganov(request):
    return render(
        request,
        'kaganov.html',
    )


# Страница с информацией о Д. М. Жуке
def zhuk(request):
    return render(
        request,
        'zhuk.html',
    )


# Страница с информацией о А. П. Карпенко
def karpenko(request):
    return render(
        request,
        'karpenko.html',
    )


# Страница с информацией о В. Г. Редько
def redko(request):
    return render(
        request,
        'redko.html',
    )


# Страница с информацией о А. С. Ющенко
def yushenko(request):
    return render(
        request,
        'yushenko.html',
    )


# Страница оргкомитета
def committee(request):
    return render(
        request,
        'committee.html',
    )


# Страница плана семинаров
def plan(request):
    return render(
        request,
        'plan.html',
    )


# Страница литературы
def literature(request):
    return render(
        request,
        'literature.html',
    )

home/templates/home/announce_list.html
{% extends "base.html" %}


{% block content %}


<br>
<br>
<br>
{% block tagName %}
{% endblock %}
{% if announce_list %}

{% for announce in announce_list %}
<div class="container content-width3" style="--font-size:20px;">
    <div class="header reader-header reader-show-element">
        <a class="domain reader-domain">
            {{ announce.author.first_name }} {{ announce.author.last_name }}
        </a>
        <div class="domain-border"></div>
        <h1 class="reader-title">
            {{ announce.title }}
        </h1>
        <div class="meta-data">
            <div class="reader-estimated-time">{{ announce.publication_date }}</div>
        </div>
        <div class="credits reader-credits">
            {% for tag in announce.announce_tags.all %}
            <a class="text-muted" href="{% url 'tag-announces' tag.tag_ID %}">
                {{tag.name}}
                {% if not forloop.last %}, {% endif %}
            </a>
            {% endfor %}
        </div>
    </div>

    <hr>

    <div class="content">
        <div class="moz-reader-content line-height4 reader-show-element">
            <div id="readability-page-1" class="page">
                <div id="myTabContent">
                    {% if announce.preview_image %}
                    <p>
                        <img src="{{ announce.preview_image.url }}" style="width: 100%; display: block;">
                    </p>
                    {% endif %}
                    <p><big>{{ announce.headline }}</big></p>
                    {% if announce.document %}
                    <p>
                        <a href="{{ announce.document.url }}">
                            Скачать документ
                        </a>
                    </p>
                    {% endif %}
                    {% if announce.presentation %}
                    <p>
                        <a href="{{ announce.presentation.url }}">
                            Скачать презентацию
                        </a>
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% if announce in user.profile.want_to_go_announces.all %}
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'want-to-go' announce.announce_ID %}'">
        Передумал идти ({{announce.profile_set.all.count}})
    </button>
    {% else %}
    <button type="button" class="btn btn-outline-primary"
            onclick="location.href='{% url 'want-to-go' announce.announce_ID %}'">
        Хочу пойти ({{announce.profile_set.all.count}})
    </button>
    {% endif %}


    <button type="button" class="btn btn-primary" data-toggle="collapse"
            data-target="#commentdiv{{ announce.announce_ID }}">
        Комментарии ({{announce.comment_set.all.count}})
    </button>
    <div id="commentdiv{{ announce.announce_ID }}" class="collapse">
        {% for comment in announce.comment_set.all %}
        <br>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ comment.user }}</h4>
                <h6 class="card-subtitle mb-2 text-muted">{{ comment.date }}</h6>
                <p class="card-text">
                    {{ comment.content }}
                </p>
            </div>
        </div>
        {% endfor %}
        <br>

        <form action="{% url 'add-comment' announce.announce_ID %}" method="post">
            {% csrf_token %}
            <input id="comment_announce_{{ announce.announce_ID }}" type="text"
                   name="comment_field_{{ announce.announce_ID }}" value="">
            <input value="Добавить комментарий" class="btn btn-primary" type="submit">
        </form>

    </div>
</div>
<hr>
{% endfor %}
{% else %}
<p>На данный момент объявлений нет</p>
{% endif %}
{% endblock %}

{% block kaganovblock %}
<div class="col-lg-3">
    <div>
        <h3 style="font-size:24px;">Основатель семинара</h3>
        <div style="background:#eee; padding:10px; ">
            <div style="text-align:center;">
                <span style="color: #2C3E50;"><b>Юрий Тихонович Каганов</b></span>
                <br><br>
                {% load static %}
                <img src="{% static 'home/images/kaganov.jpg' %}" style="margin:0 auto;" border="0">
                <hr>
                <a href="{% url 'kaganov' %}" class="btn btn-primary btn-lg">Подробнее</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/tag_announce_list.html
{% extends "home/announce_list.html" %}

    {% block tagName %}
    {% if tag %}
        <h2 style="text-align: center">{{tag.name}}</h2>
        <hr>
    {% endif %}
    {% endblock %}